//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Key]
        public int id { get; set; }

        [StringLength(250, MinimumLength = 1, ErrorMessage = "First name must be under 251 characters.")]
        public string firstName { get; set; }

        [StringLength(250, MinimumLength = 1, ErrorMessage = "First name must be under 251 characters.")]
        public string middleName { get; set; }

        [StringLength(250, MinimumLength = 1, ErrorMessage = "First name must be under 251 characters.")]
        public string lastName { get; set; }
        public Nullable<bool> isPartTime { get; set; }
        public Nullable<bool> remote { get; set; }
        public Nullable<int> positionId { get; set; }
        public Nullable<int> officeId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    }
}
