//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int id { get; set; }
        public string officeName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalCode { get; set; }
        public Nullable<int> regionId { get; set; }
        public Nullable<bool> hasParkingLot { get; set; }
        public string summary { get; set; }
        public Nullable<bool> hiring { get; set; }
    }
}
